name: CI

on:
  push:
    branches:
      - dev-branch
  pull_request:
    branches:
      - dev-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Update to the latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Update to the latest version
      with:
        python-version: '3.9'  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add your test commands here, e.g.:
        python manage.py test
